server:
  applicationConnectors:
    - type: http
      port: ${AR_SERVER_PORT:-8080}

externalBaseUrl: ${AR_EXTERNAL_BASE_URL:-http://localhost:8080}

pageSize: 100

mongodbURL: "mongodb://localhost/"

logging:
  level: INFO
  loggers:
    nl.knaw.huc: DEBUG
