server:
  applicationConnectors:
    - type: http
      port: ${AR_SERVER_PORT:-8080}

externalBaseUrl: ${AR_EXTERNAL_BASE_URL:-http://localhost:8080}

pageSize: ${AR_PAGE_SIZE:-100}

mongodbURL: ${AR_MONGODB_URL:-mongodb://localhost/}
databaseName: ${AR_DB_NAME:-annorepo}

rangeSelectorType: ${AR_RANGE_SELECTOR_TYPE:-urn:republic:TextAnchorSelector}

logging:
  level: INFO
  loggers:
    nl.knaw.huc: DEBUG
    org: WARN
    org.glassfish: ERROR
