version: '2'

services:
  annorepo_server:
    container_name: annorepo_server
    environment:
      - VIRTUAL_HOST=annorepo.tt.di.huc.knaw.nl
      - VIRTUAL_PORT=8080
      - AR_EXTERNAL_BASE_URL=https://annorepo.tt.di.huc.knaw.nl
      #      - AR_MONGODB_URL=mongodb://admin:ItsVeryVerySecret@annorepo_mongodb/
      - AR_MONGODB_URL=mongodb://annorepo_mongodb/
      - AR_DB_NAME=annorepo
      - AR_PAGE_SIZE=100
      - AR_WITH_AUTHENTICATION=true
      - AR_ROOT_API_KEY=9ac93a6a-277a-42f1-bd38-c38ea8ac3c45
    expose:
      - 8080
      - 8081
    image: registry.diginfra.net/tt/annorepo:0.4.1-alpha-3
    networks:
      - annorepo_network
      - nginxproxynetwork
    restart: unless-stopped
    tty: true
    depends_on:
      - annorepo_mongodb

  annorepo_mongodb:
    container_name: annorepo_mongodb
    #    environment:
    #      - MONGO_INITDB_ROOT_USERNAME=admin
    #      - MONGO_INITDB_ROOT_PASSWORD=ItsVeryVerySecret
    expose:
      - 27017
    image: mongo:5.0.9
    networks:
      - annorepo_network
    restart: unless-stopped
    tty: true
    volumes:
      - annorepo_mongodb_data:/data/db:rw

  annorepo_updater:
    container_name: annorepo_updater
    depends_on:
      - annorepo_server
    environment:
      - AR_ADMIN_BACKEND=http://annorepo_server:8081
    image: registry.diginfra.net/tt/annorepo-updater:0.3.0
    networks:
      - annorepo_network
    restart: "no"
    tty: true

networks:
  annorepo_network:
  nginxproxynetwork:
    external:
      name: nginxproxynetwork

volumes:
  annorepo_mongodb_data:
    driver: local